version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    env_file:
      - .env
